version: '3.9'
services:
  keycloak-server:
    hostname: keycloak-server
    container_name: keycloak-server
    image: quay.io/keycloak/keycloak:24.0.1
    command: start-dev --import-realm --features=scripts --hostname-strict=false --hostname-url=http://keycloak-server:8080
    ports:
      - "8090:8080"
    environment:
      KEYCLOAK_ADMIN: mlisena
      KEYCLOAK_ADMIN_PASSWORD: A8424628
    networks:
      - application-network
    volumes:
      - ./keycloak-export:/opt/keycloak/data/import

networks:
  application-network:
    external: true
    driver: bridge