version: '3.9'
services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.1
    command: start-dev --import-realm
    ports:
      - "8889:8080"
    environment:
      KEYCLOAK_ADMIN: mlisena
      KEYCLOAK_ADMIN_PASSWORD: A8424628
    volumes:
      - ./keycloak-export:/opt/keycloak/data/import

networks:
  application-network:
    external: true
    driver: bridge